### ISSUE TITLE
how the median in the experimental results was calculated

### ISSUE THREAD

**Issue by bb1885566** [jhauret/eben#11]
I would like to ask how the median in the experimental results was calculated. From the provided source code, it seems that the mean is being calculated instead of the median.

**Comment by jhauret** [comment]
Hi, sorry for the confusion. In the public code release, we only implemented the mean. It is shorter to implement, but does not match the README.md and article tables. 

The reported medians were obtained by calculating the metrics on the 2426 test utterances, saving the array, and then calculating the median and interquartile range.

**Comment by bb1885566** [comment]
Hi,

Thank you for the clarification. I appreciate you taking the time to explain how the medians were obtained.
