### ISSUE TITLE
The discriminator's loss function is decreasing, but the generator's loss function is increasing.

### ISSUE THREAD

**Issue by andyye1999** [jhauret/eben#4]
When I switched the dataset to bone conduction speech, where the input is a bone conduction audio signal and the label is an air conduction audio signal, this situation occurred during training.

**Comment by jhauret** [comment]
Hi,

This is not an issue. The objective metrics are still increasing during training (STOI,PESQ, SI-SDR). Please read the [discussion](https://github.com/jhauret/eben/discussions/1) for more information.
